server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catperjalanan
    username: postgres
    password: monstar
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: base
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: afiananwar2@gmail.com
    password: xxbvlphpcxceywys
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 30000
          timeout: 30000
    protocol: smtp
    test-connection: false
