server:
  port: 5432
spring:
  datasource:
    url: jdbc:postgresql://ec2-3-218-171-44.compute-1.amazonaws.com:5432/d2slhss8bs7k75
    username: tywkfsbovadonh
    password: 2e194a0b4ea1ad4024dbf0b3189384c7726710245b7279c59e98cc39492ef387
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: base
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: afiananwar2@gmail.com
    password: xxbvlphpcxceywys
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 30000
          timeout: 30000
    protocol: smtp
    test-connection: false
